// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXhS2QXc-SnJ-_imo4lYN1W0Nj5jKAQw',
    appId: '1:318028439438:android:16ff08dbe48fb945408edf',
    messagingSenderId: '318028439438',
    projectId: 'college-project-76c98',
    storageBucket: 'college-project-76c98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbprAxIlSYTtCI2FIFAR3BdLexzniyu8U',
    appId: '1:318028439438:ios:6823f0ead78a5b94408edf',
    messagingSenderId: '318028439438',
    projectId: 'college-project-76c98',
    storageBucket: 'college-project-76c98.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhvwsjUJTtQmbUYLtdRpVkZgS0VU5tCA',
    appId: '1:318028439438:web:dd36ddf5a704abda408edf',
    messagingSenderId: '318028439438',
    projectId: 'college-project-76c98',
    authDomain: 'college-project-76c98.firebaseapp.com',
    storageBucket: 'college-project-76c98.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbprAxIlSYTtCI2FIFAR3BdLexzniyu8U',
    appId: '1:318028439438:ios:6823f0ead78a5b94408edf',
    messagingSenderId: '318028439438',
    projectId: 'college-project-76c98',
    storageBucket: 'college-project-76c98.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGhvwsjUJTtQmbUYLtdRpVkZgS0VU5tCA',
    appId: '1:318028439438:web:8c2807e9b8d59494408edf',
    messagingSenderId: '318028439438',
    projectId: 'college-project-76c98',
    authDomain: 'college-project-76c98.firebaseapp.com',
    storageBucket: 'college-project-76c98.firebasestorage.app',
  );

}